import { NextResponse } from "next/server"
import { readTable, writeTable } from "../../../../lib/store"
import { createTask } from "../../../../lib/marketplace"

export const dynamic = "force-dynamic"

// ── POST /api/marketplace/procurement ─────────────────────────────────
// Public "Sell Your Car" submission — a website visitor offers a vehicle
// to a specific dealer, with zero login required (same pattern as
// /api/marketplace/book and /api/marketplace/inspection). Lands directly
// in that dealer's Procurement pipeline (app/dealer/page.js
// ProcurementSection), status NEW, source "Website".
export async function POST(req) {
  const body = await req.json()
  const { dealership, sellerName, sellerPhone, sellerEmail, brand, model, variant, year, km, fuelType, color, condition, askingPrice, message } = body

  if (!dealership || !sellerName?.trim() || !sellerPhone?.trim() || !brand?.trim() || !model?.trim()) {
    return NextResponse.json({ error: "dealership, sellerName, sellerPhone, brand and model are required" }, { status: 400 })
  }
  if (sellerPhone.replace(/\D/g, "").length < 10) {
    return NextResponse.json({ error: "Enter a valid 10-digit phone number" }, { status: 400 })
  }

  const users = await readTable("users")
  const dealer = users.find(u => u.dealership === dealership && u.role === "dealer" && u.is_active !== false)
  if (!dealer) return NextResponse.json({ error: "Dealer not found" }, { status: 404 })

  const now = new Date().toISOString()
  const row = {
    id: `proc_${Date.now()}`,
    dealership,
    sellerName: sellerName.trim(),
    sellerPhone: sellerPhone.trim(),
    sellerEmail: sellerEmail?.trim() || "",
    brand: brand.trim(),
    model: model.trim(),
    variant: variant?.trim() || "",
    year: year ? Number(year) : null,
    km: km ? Number(km) : null,
    fuelType: fuelType || "Petrol",
    color: color?.trim() || "",
    condition: condition || "Good",
    askingPrice: askingPrice ? Number(askingPrice) : null,
    offeredPrice: null,
    finalPrice: null,
    status: "NEW",
    source: "Website",
    assignedRep: null,
    inspectionDate: null,
    convertedToInventoryId: null,
    notes: message?.trim() ? [{ text: message.trim(), author: sellerName.trim(), at: now }] : [],
    createdAt: now,
    updatedAt: now,
  }

  const rows = await readTable("procurement")
  rows.unshift(row)
  await writeTable("procurement", rows)

  const feed = await readTable("feed")
  feed.unshift({
    id: `feed_${Date.now()}`,
    dealership,
    type: "PROCUREMENT_INQUIRY",
    label: "💰 SELLER WANTS TO SELL",
    msg: `${sellerName} wants to sell their ${brand} ${model}`,
    sub: `${askingPrice ? `Asking ₹${Number(askingPrice).toLocaleString("en-IN")}` : "No asking price given"} · Website`,
    icon: "🔑",
    color: "#2563EB",
    actionLabel: "Call",
    created_at: now,
  })
  await writeTable("feed", feed)

  await createTask({
    dealership,
    title: `Follow up with seller ${row.sellerName} — ${row.brand} ${row.model}`,
    type: "procurement",
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    autoGenerated: true,
  })

  if (row.sellerEmail) {
    try {
      const { sendProcurementInquiryEmail } = require("../../../../lib/email")
      await sendProcurementInquiryEmail({ to: row.sellerEmail, sellerName: row.sellerName, dealerName: dealer.dealershipName, brand: row.brand, model: row.model })
    } catch (e) {
      console.error("[Email Error] Failed to send procurement confirmation:", e.message)
    }
  }

  return NextResponse.json({
    success: true,
    procurement: { id: row.id, dealerName: dealer.dealershipName, brand: row.brand, model: row.model, status: "NEW" },
  })
}
