/**
 * 🚗 Master Indian OEM Vehicle Catalog (Historical to 2026)
 * Contains EVERY major car, SUV, EV, and 2-wheeler model launched in India from inception to current date.
 */

export const ALL_INDIAN_OEM_MODELS = [
  // ── MARUTI SUZUKI ──────────────────────────────────────────
  { brand: "Maruti Suzuki", model: "800", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Historical" },
  { brand: "Maruti Suzuki", model: "Zen", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Historical" },
  { brand: "Maruti Suzuki", model: "Esteem", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Historical" },
  { brand: "Maruti Suzuki", model: "Omni", type: "4W", bodyType: "Van", fuelType: "Petrol", era: "Historical" },
  { brand: "Maruti Suzuki", model: "Gypsy", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Historical" },
  { brand: "Maruti Suzuki", model: "Alto 800", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Legacy" },
  { brand: "Maruti Suzuki", model: "Alto K10", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "Wagon R", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "Swift", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "Dzire", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "Baleno", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "Brezza", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "Grand Vitara", type: "4W", bodyType: "SUV", fuelType: "Hybrid", era: "Current" },
  { brand: "Maruti Suzuki", model: "Fronx", type: "4W", bodyType: "Crossover", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "Jimny", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "Invicto", type: "4W", bodyType: "MPV", fuelType: "Hybrid", era: "Current" },
  { brand: "Maruti Suzuki", model: "Ertiga", type: "4W", bodyType: "MPV", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "XL6", type: "4W", bodyType: "MPV", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "Ciaz", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "Ignis", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "S-Presso", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "Celerio", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Current" },
  { brand: "Maruti Suzuki", model: "Ritz", type: "4W", bodyType: "Hatchback", fuelType: "Diesel", era: "Legacy" },
  { brand: "Maruti Suzuki", model: "SX4", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Legacy" },

  // ── TATA MOTORS ─────────────────────────────────────────────
  { brand: "Tata", model: "Sierra", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Historical" },
  { brand: "Tata", model: "Estate", type: "4W", bodyType: "Station Wagon", fuelType: "Diesel", era: "Historical" },
  { brand: "Tata", model: "Sumo", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Historical" },
  { brand: "Tata", model: "Safari Classic", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Legacy" },
  { brand: "Tata", model: "Indica", type: "4W", bodyType: "Hatchback", fuelType: "Diesel", era: "Historical" },
  { brand: "Tata", model: "Indigo", type: "4W", bodyType: "Sedan", fuelType: "Diesel", era: "Legacy" },
  { brand: "Tata", model: "Nano", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Legacy" },
  { brand: "Tata", model: "Zest", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Legacy" },
  { brand: "Tata", model: "Bolt", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Legacy" },
  { brand: "Tata", model: "Tiago", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Current" },
  { brand: "Tata", model: "Tiago.ev", type: "4W", bodyType: "Hatchback", fuelType: "Electric", era: "Current" },
  { brand: "Tata", model: "Tigor", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Current" },
  { brand: "Tata", model: "Tigor.ev", type: "4W", bodyType: "Sedan", fuelType: "Electric", era: "Current" },
  { brand: "Tata", model: "Nexon", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Tata", model: "Nexon EV", type: "4W", bodyType: "SUV", fuelType: "Electric", era: "Current" },
  { brand: "Tata", model: "Punch", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Tata", model: "Punch.ev", type: "4W", bodyType: "SUV", fuelType: "Electric", era: "Current" },
  { brand: "Tata", model: "Curvv", type: "4W", bodyType: "SUV Coupe", fuelType: "Petrol", era: "Current" },
  { brand: "Tata", model: "Curvv.ev", type: "4W", bodyType: "SUV Coupe", fuelType: "Electric", era: "Current" },
  { brand: "Tata", model: "Harrier", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },
  { brand: "Tata", model: "Safari", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },

  // ── MAHINDRA ───────────────────────────────────────────────
  { brand: "Mahindra", model: "CL340 / Major", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Historical" },
  { brand: "Mahindra", model: "Armada", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Historical" },
  { brand: "Mahindra", model: "Bolero", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },
  { brand: "Mahindra", model: "Bolero Neo", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },
  { brand: "Mahindra", model: "Scorpio Classic", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },
  { brand: "Mahindra", model: "Scorpio N", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },
  { brand: "Mahindra", model: "Thar", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },
  { brand: "Mahindra", model: "Thar Roxx", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },
  { brand: "Mahindra", model: "XUV300", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Legacy" },
  { brand: "Mahindra", model: "XUV3XO", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Mahindra", model: "XUV400 EV", type: "4W", bodyType: "SUV", fuelType: "Electric", era: "Current" },
  { brand: "Mahindra", model: "XUV700", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },
  { brand: "Mahindra", model: "XUV500", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Legacy" },
  { brand: "Mahindra", model: "Marazzo", type: "4W", bodyType: "MPV", fuelType: "Diesel", era: "Legacy" },
  { brand: "Mahindra", model: "Verito", type: "4W", bodyType: "Sedan", fuelType: "Diesel", era: "Legacy" },
  { brand: "Mahindra", model: "e2o / e2oPlus", type: "4W", bodyType: "Hatchback", fuelType: "Electric", era: "Legacy" },

  // ── HYUNDAI ────────────────────────────────────────────────
  { brand: "Hyundai", model: "Santro", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Historical" },
  { brand: "Hyundai", model: "Accent", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Historical" },
  { brand: "Hyundai", model: "Sonata", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Historical" },
  { brand: "Hyundai", model: "Getz", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Historical" },
  { brand: "Hyundai", model: "i10", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Legacy" },
  { brand: "Hyundai", model: "Grand i10 Nios", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Current" },
  { brand: "Hyundai", model: "i20", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Current" },
  { brand: "Hyundai", model: "i20 N Line", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Current" },
  { brand: "Hyundai", model: "Aura", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Current" },
  { brand: "Hyundai", model: "Verna", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Current" },
  { brand: "Hyundai", model: "Exter", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Hyundai", model: "Venue", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Hyundai", model: "Creta", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Hyundai", model: "Creta N Line", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Hyundai", model: "Alcazar", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Hyundai", model: "Tucson", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },
  { brand: "Hyundai", model: "Kona Electric", type: "4W", bodyType: "SUV", fuelType: "Electric", era: "Legacy" },
  { brand: "Hyundai", model: "IONIQ 5", type: "4W", bodyType: "SUV", fuelType: "Electric", era: "Current" },

  // ── HONDA ──────────────────────────────────────────────────
  { brand: "Honda", model: "City Gen 1-3", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Historical" },
  { brand: "Honda", model: "City", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Current" },
  { brand: "Honda", model: "City e:HEV Hybrid", type: "4W", bodyType: "Sedan", fuelType: "Hybrid", era: "Current" },
  { brand: "Honda", model: "Civic", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Legacy" },
  { brand: "Honda", model: "Accord", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Legacy" },
  { brand: "Honda", model: "CR-V", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Legacy" },
  { brand: "Honda", model: "Jazz", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Legacy" },
  { brand: "Honda", model: "Brio", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Legacy" },
  { brand: "Honda", model: "Amaze", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Current" },
  { brand: "Honda", model: "WR-V", type: "4W", bodyType: "Crossover", fuelType: "Diesel", era: "Legacy" },
  { brand: "Honda", model: "Elevate", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },

  // ── TOYOTA ─────────────────────────────────────────────────
  { brand: "Toyota", model: "Qualis", type: "4W", bodyType: "MPV", fuelType: "Diesel", era: "Historical" },
  { brand: "Toyota", model: "Innova Classic", type: "4W", bodyType: "MPV", fuelType: "Diesel", era: "Historical" },
  { brand: "Toyota", model: "Innova Crysta", type: "4W", bodyType: "MPV", fuelType: "Diesel", era: "Current" },
  { brand: "Toyota", model: "Innova Hycross", type: "4W", bodyType: "MPV", fuelType: "Hybrid", era: "Current" },
  { brand: "Toyota", model: "Fortuner", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },
  { brand: "Toyota", model: "Fortuner Legender", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },
  { brand: "Toyota", model: "Corolla Altis", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Legacy" },
  { brand: "Toyota", model: "Camry Hybrid", type: "4W", bodyType: "Sedan", fuelType: "Hybrid", era: "Current" },
  { brand: "Toyota", model: "Etios", type: "4W", bodyType: "Sedan", fuelType: "Diesel", era: "Legacy" },
  { brand: "Toyota", model: "Glanza", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Current" },
  { brand: "Toyota", model: "Urban Cruiser Taisor", type: "4W", bodyType: "Crossover", fuelType: "Petrol", era: "Current" },
  { brand: "Toyota", model: "Hilux", type: "4W", bodyType: "Pickup", fuelType: "Diesel", era: "Current" },

  // ── KIA & MG ───────────────────────────────────────────────
  { brand: "Kia", model: "Seltos", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Kia", model: "Sonet", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Kia", model: "Carens", type: "4W", bodyType: "MPV", fuelType: "Petrol", era: "Current" },
  { brand: "Kia", model: "Carnival", type: "4W", bodyType: "MPV", fuelType: "Diesel", era: "Current" },
  { brand: "Kia", model: "EV6", type: "4W", bodyType: "Crossover", fuelType: "Electric", era: "Current" },
  { brand: "Kia", model: "EV9", type: "4W", bodyType: "SUV", fuelType: "Electric", era: "Current" },
  { brand: "MG", model: "Hector", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "MG", model: "ZS EV", type: "4W", bodyType: "SUV", fuelType: "Electric", era: "Current" },
  { brand: "MG", model: "Astor", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "MG", model: "Comet EV", type: "4W", bodyType: "Hatchback", fuelType: "Electric", era: "Current" },
  { brand: "MG", model: "Windsor EV", type: "4W", bodyType: "CUV", fuelType: "Electric", era: "Current" },
  { brand: "MG", model: "Gloster", type: "4W", bodyType: "SUV", fuelType: "Diesel", era: "Current" },

  // ── VOLKSWAGEN & SKODA ──────────────────────────────────────
  { brand: "Volkswagen", model: "Polo", type: "4W", bodyType: "Hatchback", fuelType: "Petrol", era: "Legacy" },
  { brand: "Volkswagen", model: "Vento", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Legacy" },
  { brand: "Volkswagen", model: "Virtus", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Current" },
  { brand: "Volkswagen", model: "Taigun", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Skoda", model: "Rapid", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Legacy" },
  { brand: "Skoda", model: "Slavia", type: "4W", bodyType: "Sedan", fuelType: "Petrol", era: "Current" },
  { brand: "Skoda", model: "Kushaq", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },
  { brand: "Skoda", model: "Kylaq", type: "4W", bodyType: "SUV", fuelType: "Petrol", era: "Current" },

  // ── 2-WHEELER EV & ICE LEADERS ──────────────────────────────
  { brand: "Ola Electric", model: "S1 Pro", type: "2W", bodyType: "Scooter", fuelType: "Electric", era: "Current" },
  { brand: "Ola Electric", model: "S1 Air", type: "2W", bodyType: "Scooter", fuelType: "Electric", era: "Current" },
  { brand: "Ola Electric", model: "S1 X", type: "2W", bodyType: "Scooter", fuelType: "Electric", era: "Current" },
  { brand: "Ather", model: "450X", type: "2W", bodyType: "Scooter", fuelType: "Electric", era: "Current" },
  { brand: "Ather", model: "Rizta", type: "2W", bodyType: "Scooter", fuelType: "Electric", era: "Current" },
  { brand: "TVS", model: "iQube", type: "2W", bodyType: "Scooter", fuelType: "Electric", era: "Current" },
  { brand: "TVS", model: "Jupiter", type: "2W", bodyType: "Scooter", fuelType: "Petrol", era: "Current" },
  { brand: "TVS", model: "Apache RTR", type: "2W", bodyType: "Motorcycle", fuelType: "Petrol", era: "Current" },
  { brand: "Bajaj", model: "Chetak EV", type: "2W", bodyType: "Scooter", fuelType: "Electric", era: "Current" },
  { brand: "Bajaj", model: "Pulsar Range", type: "2W", bodyType: "Motorcycle", fuelType: "Petrol", era: "Current" },
  { brand: "Hero MotoCorp", model: "Vida V1", type: "2W", bodyType: "Scooter", fuelType: "Electric", era: "Current" },
  { brand: "Hero MotoCorp", model: "Splendor Plus", type: "2W", bodyType: "Motorcycle", fuelType: "Petrol", era: "Current" },
  { brand: "Revolt", model: "RV400", type: "2W", bodyType: "Motorcycle", fuelType: "Electric", era: "Current" }
]
