import { NextResponse } from "next/server"
import { verifyToken } from "../../../../lib/auth"
import { readTable, writeTable } from "../../../../lib/store"
import { createTask } from "../../../../lib/marketplace"

// The set of rep-ids a given rep is allowed to see leads for: always their
// own, plus any reps they're currently covering during leave.
async function repVisibleRepIds(repId) {
  const users = await readTable("users")
  const me = users.find(u => u.role === "rep" && u.repId === repId)
  return new Set([repId, ...(me?.covers || [])])
}

export async function GET(req) {
  const token = req.headers.get("authorization")?.replace("Bearer ", "")
  const user = token ? verifyToken(token) : null
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const dealership = searchParams.get("dealership")

  let leads = await readTable("leads")
  if (dealership) leads = leads.filter(l => l.dealership === dealership)

  // Sales reps see the leads assigned to them, plus any leads of reps they've
  // been granted temporary leave-coverage over (ownership never transfers).
  // A dealer's pipeline stays sealed otherwise.
  if (user.role === "rep") {
    const allowed = await repVisibleRepIds(user.repId)
    leads = leads.filter(l => allowed.has(l.assignedRep))
  }

  // Sort by created_at descending
  leads.sort((a, b) => new Date(b.created_at) - new Date(a.created_at))

  return NextResponse.json({ success: true, leads })
}

// POST: create a lead. body.skipDuplicateCheck bypasses the 2.6 phone-based
// duplicate warning (used when the dealer explicitly confirms "add anyway").
export async function POST(req) {
  const token = req.headers.get("authorization")?.replace("Bearer ", "")
  const user = token ? verifyToken(token) : null
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const body = await req.json()
  const leads = await readTable("leads")
  const dealership = body.dealership || "hyd-d01"

  if (!body.skipDuplicateCheck && body.phone) {
    const existing = leads.find(l => l.dealership === dealership && l.phone === body.phone)
    if (existing) {
      return NextResponse.json({ error: "A lead with this phone number already exists", duplicate: existing }, { status: 409 })
    }
  }

  const newLead = {
    id: `lead_${Date.now()}`,
    dealership,
    name: body.name || "",
    phone: body.phone || "",
    email: body.email || "",
    city: body.city || "",
    vehicle: body.vehicle || "",
    status: "NEW",
    source: body.source || "direct_dashboard",
    source_context: "default",
    amount: 0,
    notes: [],
    next_followup: body.next_followup || null,
    created_at: new Date().toISOString()
  }

  leads.push(newLead)
  await writeTable("leads", leads)

  return NextResponse.json({ success: true, lead: newLead })
}

// PATCH: generic field update, OR body.addNote:{text} to append a
// timestamped note (2.9), OR body.status==="LOST" with body.lostReason (2.11)
export async function PATCH(req) {
  const token = req.headers.get("authorization")?.replace("Bearer ", "")
  const user = token ? verifyToken(token) : null
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const body = await req.json()
  const { id, addNote, ...updates } = body

  const leads = await readTable("leads")
  const idx = leads.findIndex(l => l.id === id)
  if (idx === -1) return NextResponse.json({ error: "Lead not found" }, { status: 404 })

  // Reps may act on their own leads and on leads they're covering during
  // another rep's leave, but may never reassign a lead (only the dealer
  // controls who owns which lead).
  if (user.role === "rep") {
    const allowed = await repVisibleRepIds(user.repId)
    if (!allowed.has(leads[idx].assignedRep)) {
      return NextResponse.json({ error: "This lead is not assigned to you" }, { status: 403 })
    }
    if ("assignedRep" in updates) delete updates.assignedRep
  }

  // 9.5 Auto Task on Status Change — a lead going HOT or QUOTED needs a
  // same-day follow-up with no manual step required.
  const prevStatus = leads[idx].status
  if (updates.status && updates.status !== prevStatus && ["HOT", "QUOTED"].includes(updates.status)) {
    await createTask({
      dealership: leads[idx].dealership,
      title: `Follow up with ${leads[idx].name} — moved to ${updates.status}`,
      type: "follow_up",
      relatedLeadId: id,
      dueDate: new Date(Date.now() + 24*60*60*1000).toISOString(),
      autoGenerated: true,
    })
  }

  if (addNote) {
    const author = user.email || user.sub
    const at = new Date().toISOString()
    leads[idx].notes = leads[idx].notes || []
    leads[idx].notes.unshift({
      id: `note_${Date.now()}`,
      text: addNote.text,
      channel: addNote.channel || "note",
      author,
      created_at: at,
    })
    // Outreach actions (call / whatsapp / sms / email) also stamp lastAction
    // so lead lists can show "last touch" without scanning the notes array.
    if (["call", "whatsapp", "sms", "email"].includes(addNote.channel)) {
      leads[idx].lastAction = { type: addNote.channel, at, by: author }
    }
  } else {
    leads[idx] = { ...leads[idx], ...updates }
  }
  await writeTable("leads", leads)

  return NextResponse.json({ success: true, lead: leads[idx] })
}

// DELETE: not exposed to dealers today (leads are reopened, not removed) —
// reserved for admin-only cleanup if ever needed.
