// ── app/api/dealer/procurement/route.js ──────────────────────────────
// Used-car dealer Procurement pipeline: sellers offering a vehicle TO the
// dealer (the reverse of Leads, which are buyers). A procurement lead moves
// NEW -> INSPECTION_SCHEDULED -> INSPECTED -> OFFER_MADE -> NEGOTIATING ->
// PURCHASED | REJECTED. Marking one PURCHASED auto-creates an inventory row
// (condition:"used", inspection gate PENDING — same approve-before-publish
// flow as manually-added used vehicles) so a bought car flows straight into
// the dealer's sellable stock without re-typing its details.

import { NextResponse } from "next/server"
import { verifyToken } from "../../../../lib/auth"
import { readTable, writeTable } from "../../../../lib/store"
import { createTask } from "../../../../lib/marketplace"
import { ensureModelArticle, linkVehicleToArticle } from "../../../../lib/blog"

async function getUser(req) {
  const auth = req.headers.get("authorization") || ""
  const token = auth.replace("Bearer ", "").trim()
  if (!token) return null
  try { return verifyToken(token) } catch { return null }
}

function canAccess(user, row) {
  if (["founder", "superadmin"].includes(user.role)) return true
  return (user.role === "dealer" || user.role === "rep") && user.dealership === row.dealership
}

const PIPELINE_STATUSES = ["NEW", "INSPECTION_SCHEDULED", "INSPECTED", "OFFER_MADE", "NEGOTIATING", "PURCHASED", "REJECTED"]

// GET: procurement leads for the caller's dealership
export async function GET(req) {
  const user = await getUser(req)
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const dealership = user.dealership || searchParams.get("dealership")

  const all = await readTable("procurement")
  const rows = dealership ? all.filter(r => r.dealership === dealership) : all
  rows.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))
  return NextResponse.json({ success: true, procurement: rows, total: rows.length })
}

// POST: dealer/rep logs a new seller inquiry
export async function POST(req) {
  const user = await getUser(req)
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  if (!["dealer", "rep", "founder", "superadmin"].includes(user.role)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const body = await req.json()
  const { sellerName, sellerPhone, sellerEmail, brand, model, variant, year, km, fuelType, color, condition, askingPrice, source, notes } = body

  if (!sellerName?.trim() || !sellerPhone?.trim() || !brand?.trim() || !model?.trim()) {
    return NextResponse.json({ error: "sellerName, sellerPhone, brand and model are required" }, { status: 400 })
  }

  const dealership = user.dealership || body.dealership
  if (!dealership) return NextResponse.json({ error: "No dealership on this account" }, { status: 400 })

  const now = new Date().toISOString()
  const row = {
    id: `proc_${Date.now()}`,
    dealership,
    sellerName: sellerName.trim(),
    sellerPhone: sellerPhone.trim(),
    sellerEmail: sellerEmail?.trim() || "",
    brand: brand.trim(),
    model: model.trim(),
    variant: variant?.trim() || "",
    year: year ? Number(year) : null,
    km: km ? Number(km) : null,
    fuelType: fuelType || "Petrol",
    color: color?.trim() || "",
    condition: condition || "Good",
    askingPrice: askingPrice ? Number(askingPrice) : null,
    offeredPrice: null,
    finalPrice: null,
    status: "NEW",
    source: source || "Walk-in",
    assignedRep: user.role === "rep" ? user.repId : null,
    inspectionDate: null,
    convertedToInventoryId: null,
    notes: notes ? [{ text: notes.trim(), author: user.name || user.email, at: now }] : [],
    createdAt: now,
    updatedAt: now,
  }

  const rows = await readTable("procurement")
  rows.unshift(row)
  await writeTable("procurement", rows)

  await createTask({
    dealership,
    title: `Follow up with seller ${row.sellerName} — ${row.brand} ${row.model}`,
    type: "procurement",
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    autoGenerated: true,
  })

  return NextResponse.json({ success: true, procurement: row })
}

// PATCH: update status/fields, append a note, or (status=PURCHASED) convert to inventory
export async function PATCH(req) {
  const user = await getUser(req)
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  if (!["dealer", "rep", "founder", "superadmin"].includes(user.role)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const body = await req.json()
  const { id, note, ...updates } = body
  if (!id) return NextResponse.json({ error: "id is required" }, { status: 400 })

  if (updates.status && !PIPELINE_STATUSES.includes(updates.status)) {
    return NextResponse.json({ error: `Invalid status. Must be one of: ${PIPELINE_STATUSES.join(", ")}` }, { status: 400 })
  }

  const rows = await readTable("procurement")
  const idx = rows.findIndex(r => r.id === id)
  if (idx === -1) return NextResponse.json({ error: "Procurement lead not found" }, { status: 404 })
  if (!canAccess(user, rows[idx])) return NextResponse.json({ error: "Forbidden" }, { status: 403 })

  const row = rows[idx]

  if (note?.trim()) {
    row.notes = [...(row.notes || []), { text: note.trim(), author: user.name || user.email, at: new Date().toISOString() }]
  }

  const numericFields = ["offeredPrice", "finalPrice", "askingPrice", "year", "km"]
  for (const [k, v] of Object.entries(updates)) {
    row[k] = numericFields.includes(k) && v !== null && v !== "" ? Number(v) : v
  }
  row.updatedAt = new Date().toISOString()

  // Marking a lead PURCHASED converts it straight into sellable inventory —
  // condition "used", inspection gate PENDING (same approve-before-publish
  // flow every manually-added used vehicle goes through), so the dealer
  // reviews/fills the inspection checklist before it appears on the
  // marketplace rather than skipping that step just because it came from
  // procurement.
  if (updates.status === "PURCHASED" && !row.convertedToInventoryId) {
    // The JWT payload only carries { sub, email, role, dealership } — it never
    // has a display name — so user.name is always undefined here. Look up the
    // dealer's actual business name from their user record instead (same field
    // the manual Add-Vehicle form reads via /api/dealer/settings), otherwise
    // every procurement-converted listing shows a blank dealer name on the
    // public marketplace.
    const users = await readTable("users")
    const dealerUser = users.find(u => u.dealership === row.dealership && u.role === "dealer")

    const inv = await readTable("inventory")
    const vehicleId = `inv_${Date.now()}`
    inv.unshift({
      id: vehicleId,
      dealership: row.dealership,
      dealerName: dealerUser?.dealershipName || dealerUser?.name || "",
      brand: row.brand,
      model: row.model,
      variant: row.variant || "",
      type: "4W",
      bodyType: "Sedan",
      year: row.year || new Date().getFullYear(),
      km: row.km || 0,
      condition: "used",
      fuelType: row.fuelType || "Petrol",
      color: row.color || "",
      transmission: "",
      engineDetails: "",
      exShowroom: row.finalPrice || row.offeredPrice || row.askingPrice || 0,
      status: "IN_STOCK",
      vin: "",
      isDemo: false,
      features: "",
      state: dealerUser?.state || "",
      district: dealerUser?.city || "",
      tags: "",
      images: ["🚗"],
      inspectionReport: { categories: [], overallGrade: "B", approvalStatus: "PENDING" },
      procurementSourceId: row.id,
      createdAt: new Date().toISOString(),
    })
    await writeTable("inventory", inv)
    row.convertedToInventoryId = vehicleId

    // Same model-hub auto-generation as manual Add Vehicle (app/api/dealer/
    // inventory/route.js) — without this, used-car dealers' purchased stock
    // never gets an SEO article, even though Procurement is the primary
    // inventory-entry path for that whole dealer segment.
    const newVehicle = inv.find(v => v.id === vehicleId)
    const articleId = await ensureModelArticle(newVehicle, { dealership: row.dealership, name: dealerUser?.dealershipName || dealerUser?.name })
    if (articleId) {
      await linkVehicleToArticle(vehicleId, articleId)
    }
  }

  rows[idx] = row
  await writeTable("procurement", rows)

  return NextResponse.json({ success: true, procurement: row })
}
