import { NextResponse } from "next/server"
import fs from "fs"
import path from "path"
import { verifyToken } from "../../../../lib/auth"
import { readJson, updateBooking, finalizeSale, createTask } from "../../../../lib/marketplace"
import { capturePayment, refundPayment, createTransfer, isRazorpayConfigured } from "../../../../lib/razorpay"

const BOOK_FILE    = path.join(process.cwd(), "data", "bookings.json")
const DEALERS_FILE = path.join(process.cwd(), "data", "dealers.json")

async function getUser(req) {
  const auth = req.headers.get("authorization") || ""
  const token = auth.replace("Bearer ", "").trim()
  if (!token) return null
  try { return verifyToken(token) } catch { return null }
}

function canAccess(user, booking) {
  if (["founder", "superadmin"].includes(user.role)) return true
  return user.role === "dealer" && user.dealership === booking.dealership
}

// GET: bookings for the dealer's own dealership
export async function GET(req) {
  const user = await getUser(req)
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const dealership = user.dealership || searchParams.get("dealership")

  const all = await readJson(BOOK_FILE)
  const bookings = dealership ? all.filter(b => b.dealership === dealership) : all
  return NextResponse.json({ success: true, bookings, total: bookings.length })
}

// PATCH: action=finalize (capture held funds + attempt payout) | action=cancel (refund) |
//        action=schedule (assign rep + slot) | action=outcome (test drive result) |
//        action=noshow (buyer didn't show)
export async function PATCH(req) {
  const user = await getUser(req)
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  if (!["dealer", "founder", "superadmin"].includes(user.role)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const body = await req.json()
  const { id, action } = body
  if (!id || !action) return NextResponse.json({ error: "id and action are required" }, { status: 400 })

  const booking = (await readJson(BOOK_FILE)).find(b => b.id === id)
  if (!booking) return NextResponse.json({ error: "Booking not found" }, { status: 404 })
  if (!canAccess(user, booking)) return NextResponse.json({ error: "Forbidden" }, { status: 403 })

  // 3.1 Test Drive Scheduler — assign rep + confirmed date/time
  if (action === "schedule") {
    const { assignedRep, scheduledTime } = body
    // 3.3 Vehicle Availability Check — same vehicle, same day, already scheduled elsewhere
    if (scheduledTime) {
      const all = await readJson(BOOK_FILE)
      const day = new Date(scheduledTime).toDateString()
      const conflict = all.find(b => b.id !== id && b.vehicleId === booking.vehicleId && b.scheduledTime && new Date(b.scheduledTime).toDateString() === day && b.status !== "CANCELLED")
      if (conflict) return NextResponse.json({ error: `This vehicle is already booked for a test drive on ${day} (${conflict.name})` }, { status: 409 })
    }
    const updated = await updateBooking(id, { assignedRep: assignedRep ?? booking.assignedRep, scheduledTime: scheduledTime ?? booking.scheduledTime })
    return NextResponse.json({ success: true, booking: updated })
  }

  // 3.5 Test Drive Outcome + 3.6 Post-Drive Follow-up Trigger
  if (action === "outcome") {
    const { outcome } = body
    if (!["Interested", "Needs Time", "Not Interested", "Ready to Book"].includes(outcome)) {
      return NextResponse.json({ error: "Invalid outcome" }, { status: 400 })
    }
    const updated = await updateBooking(id, { outcome })
    let task = null
    if (outcome === "Interested" || outcome === "Ready to Book") {
      task = await createTask({
        dealership: booking.dealership,
        title: `Follow up with ${booking.name} — ${outcome === "Ready to Book" ? "ready to book!" : "interested after test drive"}`,
        type: "follow_up",
        dueDate: new Date(Date.now() + 24*60*60*1000).toISOString(),
        autoGenerated: true,
      })
    }
    return NextResponse.json({ success: true, booking: updated, task })
  }

  // 3.8 No-Show Tracking
  if (action === "noshow") {
    const updated = await updateBooking(id, { noShow: true, outcome: "No-Show" })
    const task = await createTask({
      dealership: booking.dealership,
      title: `Reschedule test drive — ${booking.name} didn't show (${booking.vehicleName})`,
      type: "follow_up",
      dueDate: new Date(Date.now() + 4*60*60*1000).toISOString(),
      autoGenerated: true,
    })
    return NextResponse.json({ success: true, booking: updated, task })
  }

  if (action === "finalize") {
    if (booking.paymentStatus !== "AUTHORIZED_HELD") {
      return NextResponse.json({ error: `Cannot finalize a booking with payment status ${booking.paymentStatus}` }, { status: 400 })
    }
    if (!isRazorpayConfigured()) {
      return NextResponse.json({ error: "Razorpay is not configured" }, { status: 503 })
    }
    try {
      await capturePayment(booking.razorpayPaymentId, booking.amountPaise)
      let updated = await updateBooking(id, { paymentStatus: "CAPTURED_HELD_IN_PG", status: "SALE_CONFIRMED" })

      const dealers = await readJson(DEALERS_FILE)
      const dealer = dealers.find(d => d.id === booking.dealership)
      if (dealer?.razorpayAccountId) {
        try {
          await createTransfer(booking.razorpayPaymentId, dealer.razorpayAccountId, booking.amountPaise)
          updated = await updateBooking(id, { paymentStatus: "RELEASED_TO_DEALER" })
        } catch (transferErr) {
          // Capture succeeded but payout failed/not eligible yet — funds stay
          // in the platform account, dealer can be paid out manually.
          updated = await updateBooking(id, { payoutError: transferErr.error?.description || transferErr.message })
        }
      }

      const { customer, task } = await finalizeSale(updated)
      return NextResponse.json({ success: true, booking: updated, customer, task })
    } catch (e) {
      return NextResponse.json({ error: e.error?.description || e.message || "Capture failed" }, { status: 502 })
    }
  }

  if (action === "cancel") {
    if (["REFUNDED", "CANCELLED"].includes(booking.status) || booking.paymentStatus === "REFUNDED") {
      return NextResponse.json({ error: "Booking already cancelled" }, { status: 400 })
    }
    if (["CAPTURED_HELD_IN_PG", "RELEASED_TO_DEALER"].includes(booking.paymentStatus)) {
      if (!isRazorpayConfigured()) return NextResponse.json({ error: "Razorpay is not configured" }, { status: 503 })
      try {
        await refundPayment(booking.razorpayPaymentId, booking.amountPaise, { reason: "test_drive_cancelled" })
      } catch (e) {
        return NextResponse.json({ error: e.error?.description || e.message || "Refund failed" }, { status: 502 })
      }
      const updated = await updateBooking(id, { status: "CANCELLED", paymentStatus: "REFUNDED" })
      return NextResponse.json({ success: true, booking: updated })
    }
    // AUTHORIZED_HELD (never captured) or SKIPPED_NO_GATEWAY — nothing to refund,
    // an uncaptured authorization simply expires on its own.
    const updated = await updateBooking(id, { status: "CANCELLED" })
    return NextResponse.json({ success: true, booking: updated })
  }

  return NextResponse.json({ error: "Unknown action" }, { status: 400 })
}
