import { NextResponse } from "next/server"
import path from "path"
import { verifyToken } from "../../../../lib/auth"
import { readJson, writeJson, createTask } from "../../../../lib/marketplace"

const FILE = path.join(process.cwd(), "data", "tasks.json")

async function getUser(req) {
  const auth = req.headers.get("authorization") || ""
  const token = auth.replace("Bearer ", "").trim()
  if (!token) return null
  try { return verifyToken(token) } catch { return null }
}

// GET: dealer's own tasks
export async function GET(req) {
  const user = await getUser(req)
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const dealership = user.dealership || searchParams.get("dealership")

  const all = await readJson(FILE)
  const tasks = dealership ? all.filter(t => t.dealership === dealership) : all
  return NextResponse.json({ success: true, tasks, total: tasks.length })
}

// POST: manually add a task
export async function POST(req) {
  const user = await getUser(req)
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  if (!["dealer", "founder", "superadmin"].includes(user.role)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const body = await req.json()
  const dealership = user.dealership || body.dealership

  const task = await createTask({
    dealership,
    title: body.title,
    type: body.type || "manual",
    relatedLeadId: body.relatedLeadId || null,
    relatedCustomerId: body.relatedCustomerId || null,
    dueDate: body.dueDate || null,
    assignedRep: body.assignedRep || null,
    autoGenerated: false,
  })

  return NextResponse.json({ success: true, task })
}

// PATCH: update task (mark done, edit title/due date)
export async function PATCH(req) {
  const user = await getUser(req)
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const body = await req.json()
  const { id, ...updates } = body
  if (!id) return NextResponse.json({ error: "id required" }, { status: 400 })

  const tasks = await readJson(FILE)
  const idx = tasks.findIndex(t => t.id === id)
  if (idx === -1) return NextResponse.json({ error: "Not found" }, { status: 404 })
  if (user.role === "dealer" && tasks[idx].dealership !== user.dealership) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  tasks[idx] = { ...tasks[idx], ...updates, updatedAt: new Date().toISOString() }
  await writeJson(FILE, tasks)

  return NextResponse.json({ success: true, task: tasks[idx] })
}

// DELETE: remove a task
export async function DELETE(req) {
  const user = await getUser(req)
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const id = searchParams.get("id")
  if (!id) return NextResponse.json({ error: "id required" }, { status: 400 })

  let tasks = await readJson(FILE)
  const target = tasks.find(t => t.id === id)
  if (!target) return NextResponse.json({ error: "Not found" }, { status: 404 })
  if (user.role === "dealer" && target.dealership !== user.dealership) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  tasks = tasks.filter(t => t.id !== id)
  await writeJson(FILE, tasks)
  return NextResponse.json({ success: true })
}
