import { NextResponse } from "next/server"
import { readJson, writeJson, findVehicle, createTask } from "../../../../lib/marketplace"
import path from "path"

const BOOK_FILE  = path.join(process.cwd(), "data", "bookings.json")
const LEADS_FILE = path.join(process.cwd(), "data", "leads.json")
const FEED_FILE  = path.join(process.cwd(), "data", "feed.json")

export const dynamic = "force-dynamic"

export async function POST(req) {
  const body = await req.json()
  const { vehicleId, name, phone, email, inspectionDate, inspectionTime, message } = body

  if (!vehicleId || !name || !phone || !inspectionDate || !inspectionTime) {
    return NextResponse.json(
      { error: "vehicleId, name, phone, inspectionDate, and inspectionTime are required" },
      { status: 400 }
    )
  }

  if (phone.replace(/\D/g, "").length < 10) {
    return NextResponse.json({ error: "Enter a valid 10-digit phone number" }, { status: 400 })
  }

  const vehicle = await findVehicle(vehicleId)
  if (!vehicle) return NextResponse.json({ error: "Vehicle not found" }, { status: 404 })

  const now = new Date().toISOString()
  const bookingId = `insp_${Date.now()}`

  const booking = {
    id: bookingId,
    type: "INSPECTION",
    vehicleId,
    vehicleName: `${vehicle.brand} ${vehicle.model} ${vehicle.variant || ""}`.trim(),
    dealership: vehicle.dealership,
    dealerName: vehicle.dealerName,
    name,
    phone,
    email: email || "",
    inspectionDate,
    inspectionTime,
    preferredDate: inspectionDate,
    message: message || "",
    tokenAmount: 0,
    status: "CONFIRMED",
    paymentStatus: "NOT_APPLICABLE",
    createdAt: now,
  }

  const bookings = await readJson(BOOK_FILE)
  bookings.unshift(booking)
  await writeJson(BOOK_FILE, bookings)

  const lead = {
    id: `lead_${Date.now()}`,
    dealership: vehicle.dealership,
    name,
    phone,
    email: email || "",
    vehicle: `${vehicle.brand} ${vehicle.model} ${vehicle.variant || ""}`.trim(),
    vehicleId,
    status: "HOT",
    source: "marketplace_booking",
    source_context: "inspection",
    amount: 0,
    tokenCollected: 0,
    message: message || "",
    bookingId,
    preferredDate: inspectionDate,
    created_at: now,
  }
  const leads = await readJson(LEADS_FILE)
  leads.unshift(lead)
  await writeJson(LEADS_FILE, leads)

  const dateStr = new Date(inspectionDate).toLocaleDateString("en-IN", { day: "numeric", month: "short" })
  const feedEvent = {
    id: `feed_${Date.now()}`,
    dealership: vehicle.dealership,
    type: "INSPECTION_BOOKED",
    label: "🔍 INSPECTION BOOKED",
    msg: `${name} booked mechanic inspection — ${vehicle.model}`,
    sub: `${dateStr} at ${inspectionTime} · Customer's own mechanic`,
    icon: "🔧",
    color: "#2563EB",
    actionLabel: "Call",
    created_at: now,
  }
  const feed = await readJson(FEED_FILE)
  feed.unshift(feedEvent)
  await writeJson(FEED_FILE, feed)

  await createTask({
    dealership: vehicle.dealership,
    title: `Inspection visit: ${name} — ${vehicle.model} (${dateStr} ${inspectionTime})`,
    type: "inspection",
    relatedLeadId: lead.id,
    dueDate: new Date(inspectionDate).toISOString(),
    autoGenerated: true,
  })

  if (email) {
    try {
      const { sendInspectionBookingEmail } = require("../../../../lib/email")
      await sendInspectionBookingEmail({ to: email, name, booking, vehicle })
    } catch (e) {
      console.error("[Email Error] Failed to send inspection booking confirmation:", e.message)
    }
  }

  return NextResponse.json({
    success: true,
    booking: {
      id: booking.id,
      type: "INSPECTION",
      vehicleName: booking.vehicleName,
      dealerName: vehicle.dealerName,
      inspectionDate: booking.inspectionDate,
      inspectionTime: booking.inspectionTime,
      status: "CONFIRMED",
    },
  })
}
